spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    template:
      exchange: spring-boot-exchange
      default-receive-queue: spring-boot-queue
      routing-key: foo.bar.#