INSERT INTO t_user_info ( USER_INFO_ACCOUNT, USER_INFO_PASSWORD, USER_INFO_AGE, USER_INFO_SEX )
VALUES
	( 'admin', '123456', 27, 1 );
	INSERT INTO t_user_info ( USER_INFO_ACCOUNT, USER_INFO_PASSWORD, USER_INFO_AGE, USER_INFO_SEX )
VALUES
	( 'root', '654321', 28, 0 );